# ============================================
# File: K8S/serviceaccount.yml
# Service Account for Pod Security
# ============================================
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hotstar-sa
  namespace: default
  labels:
    app: hotstar

